export const Data = [
 {
  id: 'cine-sunt',
  h2: 'Visul tău,',
  h2Span: 'pasiunea mea!',
  p: 'Oricât de ciudat, inovator sau  dificil  ar părea proiectul tău,',
  pSpan: 'hai să stăm de vorbă.',
  buttonLabel: 'Cum te pot ajuta',
  navBtnLabel: 'Cine sunt',
  to: 'Ce-fac',
  class: 'first',
 },
 {
  id: 'ce-fac',
  h2: 'Cum te pot ajuta?',
  p: 'E simplu. Dacă problema ta ține de partea electrică a masinii, te pot ajuta. Și nu te teme. Nu mă surprinzi. Am lucrat la multe proiecte îndrăznețe. ',
  buttonLabel: 'Vezi ce am facut',
  navBtnLabel: 'Ce fac',
  to: 'Portofoliu',
  class: 'second',
 },
 {
  id: 'faq',
  h2: 'Întrebări adresate fregvent',
  questions: [
   {
    q: 'Loi',
    a: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sed dolores! Aliquid voluptas dolorem illo, dolor in explicabo debitis labore ducimus repellat sit laborum non aperiam quod nihil quia? Consequuntur repellat maxime laboriosam similique tenetur? Sint pariatur quae doloribus, dicta aperiam mollitia inventore,',
   },
   {
    q: 'Lorem lores! Ali',
    a: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sed dolores! Aliquid voluptas dolorem illo, dolor in explicabo debitis labore ducimus repellat sit laborum non aperiam quod nihil quia? Consequuntur repellat maxime laboriosam similique tenetur? Sint pariatur quae doloribus, dicta aperiam mollitia inventore,',
   },
   {
    q: 'Lorem ipsued dolores! Ali',
    a: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sed dolores! Aliquid voluptas dolorem illo, dolor in explicabo debitis labore ducimus repellat sit laborum non aperiam quod nihil quia? Consequuntur repellat maxime laboriosam similique tenetur? Sint pariatur quae doloribus, dicta aperiam mollitia inventore,',
   },
   {
    q: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sed dolores! Ali',
    a: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sed dolores! Aliquid voluptas dolorem illo, dolor in explicabo debitis labore ducimus repellat sit laborum non aperiam quod nihil quia? Consequuntur repellat maxime laboriosam similique tenetur? Sint pariatur quae doloribus, dicta aperiam mollitia inventore,',
   },
   {
    q: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sed dolores! Ali',
    a: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sed dolores! Aliquid voluptas dolorem illo, dolor in explicabo debitis labore ducimus repellat sit laborum non aperiam quod nihil quia? Consequuntur repellat maxime laboriosam similique tenetur? Sint pariatur quae doloribus, dicta aperiam mollitia inventore,',
   },
  ],
  buttonLabel: 'Întrebări fregvente',
  navBtnLabel: 'Întrebări fregvente',
  to: 'Recenzii',
  class: 'third',
 },
 {
  id: 'portofoliu',
  h1: 'Câteva dintre lurările mele',
  p: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sed dolores! Aliquid voluptas dolorem illo, dolor in explicabo debitis labore ducimus repellat sit laborum non aperiam quod nihil quia? Consequuntur repellat maxime laboriosam similique tenetur? Sint pariatur quae doloribus, dicta aperiam mollitia inventore, illo eos expedita laudantium, nulla commodi totam.',
  buttonLabel: 'Vezi ce spune lumea',
  navBtnLabel: 'Portofoliu',
  to: 'Recenzii',
  class: 'fourth',
 },
 {
  id: 'recenzii',
  h1: 'Ce spune lumea despre mine?',
  p: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sed dolores! Aliquid voluptas dolorem illo, dolor in explicabo debitis labore ducimus repellat sit laborum non aperiam quod nihil quia? Consequuntur repellat maxime laboriosam similique tenetur? Sint pariatur quae doloribus, dicta aperiam mollitia inventore, illo eos expedita laudantium, nulla commodi totam.',
  buttonLabel: 'Contactează-mă',
  navBtnLabel: 'Recenzii',
  to: 'Contact',
  class: 'fifth',
 },
 {
  id: 'contact',
  h1: 'Ce mai astepți?',
  p: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sed dolores! Aliquid voluptas dolorem illo, dolor in explicabo debitis labore ducimus repellat sit laborum non aperiam quod nihil quia? Consequuntur repellat maxime laboriosam similique tenetur? Sint pariatur quae doloribus, dicta aperiam mollitia inventore, illo eos expedita laudantium, nulla commodi totam.',
  buttonLabel: '',
  navBtnLabel: 'Contact',
  to: '',
  class: 'sixth',
 },
];
